// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package database

import (
	"context"
	"time"
)

const countCommentsByIP = `-- name: CountCommentsByIP :one
SELECT count(*) 
FROM comments
WHERE ip_address = $1 
AND created_at > (now() - interval '1 minute')
`

func (q *Queries) CountCommentsByIP(ctx context.Context, ipAddress string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  username, 
  content, 
  ip_address
) VALUES (
  $1, $2, $3
) RETURNING id, username, content, created_at
`

type CreateCommentParams struct {
	Username  string
	Content   string
	IpAddress string
}

type CreateCommentRow struct {
	ID        int64
	Username  string
	Content   string
	CreatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Username, arg.Content, arg.IpAddress)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, username, content, created_at 
FROM comments
WHERE is_hidden = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCommentsParams struct {
	Limit  int32
	Offset int32
}

type ListCommentsRow struct {
	ID        int64
	Username  string
	Content   string
	CreatedAt time.Time
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
