// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Comment struct {
	ID        int64
	Username  string
	Content   string
	IpAddress string
	IsHidden  bool
	CreatedAt time.Time
}

type IdempotencyKey struct {
	Key          string
	UserID       int64
	ResponseCode sql.NullInt32
	ResponseBody pqtype.NullRawMessage
	CreatedAt    time.Time
}

type Order struct {
	ID        int64
	UserID    int64
	ProductID int64
	Amount    int32
	CreatedAt time.Time
}

type Product struct {
	ID          int64
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	FullName  string
	Email     string
	CreatedAt time.Time
}
