// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Comment struct {
	ID        int64
	Username  string
	Content   string
	IpAddress string
	IsHidden  bool
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	FullName  string
	Email     string
	CreatedAt time.Time
}
