// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package database

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key, user_id, response_code, response_body
) VALUES (
    $1, $2, $3, $4
) RETURNING key, user_id, response_code, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	Key          string
	UserID       int64
	ResponseCode sql.NullInt32
	ResponseBody pqtype.NullRawMessage
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, product_id, amount
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, product_id, amount, created_at
`

type CreateOrderParams struct {
	UserID    int64
	ProductID int64
	Amount    int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.ProductID, arg.Amount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, user_id, response_code, response_body, created_at FROM idempotency_keys
WHERE key= $1 AND user_id = $2
FOR UPDATE
`

type GetIdempotencyKeyParams struct {
	Key    string
	UserID int64
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.Key, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
